export const GET_ALL_SONGS_ADMIN_REQUEST = "GET_ALL_SONGS_ADMIN_REQUEST";
export const GET_ALL_SONGS_ADMIN_SUCCESS = "GET_ALL_SONGS_ADMIN_SUCCESS";
export const GET_ALL_SONGS_ADMIN_FAIL = "GET_ALL_SONGS_ADMIN_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const GET_ALL_SONGS_FROM_A_PARTICULAR_ARTIST_REQUEST =
    "GET_ALL_SONGS_FROM_A_PARTICULAR_ARTIST_REQUEST";
export const GET_ALL_SONGS_FROM_A_PARTICULAR_ARTIST_SUCCESS =
    "GET_ALL_SONGS_FROM_A_PARTICULAR_ARTIST_SUCCESS";
export const GET_ALL_SONGS_FROM_A_PARTICULAR_ARTIST_FAIL =
    "GET_ALL_SONGS_FROM_A_PARTICULAR_ARTIST_FAIL";

export const CREATE_SONG_REQUEST = "CREATE_SONG_REQUEST";
export const CREATE_SONG_SUCCESS = "CREATE_SONG_SUCCESS";
export const CREATE_SONG_FAIL = "CREATE_SONG_FAIL";

export const DELETE_SONG_REQUEST = "DELETE_SONG_REQUEST";
export const DELETE_SONG_SUCCESS = "DELETE_SONG_SUCCESS";
export const DELETE_SONG_FAIL = "DELETE_SONG_FAIL";

export const GET_LATEST_SONGS_REQUEST = "GET_LATEST_SONGS_REQUEST";
export const GET_LATEST_SONGS_SUCCESS = "GET_LATEST_SONGS_SUCCESS";
export const GET_LATEST_SONGS_FAIL = "GET_LATEST_SONGS_FAIL";

export const GET_FAVOURITE_SONGS_REQUEST = "GET_FAVOURITE_SONGS_REQUEST";
export const GET_FAVOURITE_SONGS_SUCCESS = "GET_FAVOURITE_SONGS_SUCCESS";
export const GET_FAVOURITE_SONGS_FAIL = "GET_FAVOURITE_SONGS_FAIL";

export const GET_TRENDING_SONGS_REQUEST = "GET_TRENDING_SONGS_REQUEST";
export const GET_TRENDING_SONGS_SUCCESS = "GET_TRENDING_SONGS_SUCCESS";
export const GET_TRENDING_SONGS_FAIL = "GET_TRENDING_SONGS_FAIL";

export const ADD_SONG_TO_FAVOURITES_REQUEST = "ADD_SONG_TO_FAVOURITES";
export const ADD_SONG_TO_FAVOURITES_SUCCESS = "ADD_SONG_TO_FAVOURITES_SUCCESS";
export const ADD_SONG_TO_FAVOURITES_FAIL = "ADD_SONG_TO_FAVOURITES_FAIL";

export const SEARCH_RESULT_REQUEST = "SEARCH_RESULT_REQUEST";
export const SEARCH_RESULT_SUCCESS = "SEARCH_RESULT_SUCCESS";
export const SEARCH_RESULT_FAIL = "SEARCH_RESULT_FAIL";
