export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const LOGOUT_FAIL = "LOGOUT_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";

export const GET_ALL_USERS_ADMIN_REQUEST = "GET_ALL_USERS_ADMIN_REQUEST";
export const GET_ALL_USERS_ADMIN_SUCCESS = "GET_ALL_USERS_ADMIN_SUCCESS";
export const GET_ALL_USERS_ADMIN_FAIL = "GET_ALL_USERS_ADMIN_FAIL";

export const LOAD_REQUEST = "LOAD_REQUEST";
export const LOAD_SUCCESS = "LOAD_SUCCESS";
export const LOAD_FAIL = "LOAD_FAIL";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";

export const SINGER_APPLIED_USERS_REQUEST = "SINGER_APPLIED_USERS_REQUEST";
export const SINGER_APPLIED_USERS_SUCCESS = "SINGER_APPLIED_USERS_SUCCESS";
export const SINGER_APPLIED_USERS_FAIL = "SINGER_APPLIED_USERS_FAIL";

export const GET_LATEST_ARTISTS_REQUEST = "GET_LATEST_ARTISTS_REQUEST";
export const GET_LATEST_ARTIST_SUCCESS = "GET_LATEST_ARTIST_SUCCESS";
export const GET_LATEST_ARTIST_FAIL = "GET_LATEST_ARTIST_FAIL";

export const ACCEPT_SINGER_APPLICATION_REQUEST =
    "ACCEPT_SINGER_APPLICATION_REQUEST";
export const ACCEPT_SINGER_APPLICATION_SUCCESS =
    "ACCEPT_SINGER_APPLICATION_SUCCESS";
export const ACCEPT_SINGER_APPLICATION_FAIL = "ACCEPT_SINGER_APPLICATION_FAIL";
